#!/bin/sh
USER=git
USERNAME=$USER

if ! test -d /data/gogs; then
	mkdir -p /data/gogs/data /data/gogs/conf /data/gogs/log /data/git
fi

if ! test -d ~git/.ssh; then
    mkdir ~git/.ssh
    chmod 700 ~git/.ssh
fi

if ! test -f ~git/.ssh/environment; then
    echo "GOGS_CUSTOM=/data/gogs" > ~git/.ssh/environment
    chown git:git ~git/.ssh/environment
    chown 600 ~git/.ssh/environment
fi

ln -sf /data/gogs/log  /app/gogs/log
ln -sf /data/gogs/data /app/gogs/data
ln -sf /data/gogs/conf /app/gogs/conf

chown -R git:git /data /app/gogs ~git/

export USER
export USERNAME
exec gosu $USER /app/gogs/gogs web
