#!/bin/sh
if test -n "$USER_GOGS"; then 
    export USER=$USER_GOGS 
else
    export USER=git
fi

USER_HOME=$(eval echo ~$USER)

if ! test -d $USER_HOME/.ssh; then
    gosu "$USER" mkdir -p $USER_HOME/.ssh
    chmod 700 $USER_HOME/.ssh
fi

if ! test -f $USER_HOME/.ssh/environment; then
    gosu "$USER" echo "GOGS_CUSTOM=${GOGS_CUSTOM}" > $USER_HOME/.ssh/environment
    chmod 600 $USER_HOME/.ssh/environment
fi

cd /app/gogs || exit 1

# Link volumed data with app data
ln -sfn /data/gogs/log  ./log
ln -sfn /data/gogs/data ./data

# Backward Compatibility with Gogs Container v0.6.15
ln -sfn /data/git /home/$USER

chmod 0755 /data /data/gogs $USER_HOME/
