targets:
  debian-11: &debian
    build_dependencies:
      - libpam0g-dev
    dependencies:
      - libpam0g
      - git
  debian-12:
    <<: *debian
  debian-13:
    <<: *debian
  debian-14:
    <<: *debian
  ubuntu-20.04:
    <<: *debian
  ubuntu-22.04:
    <<: *debian
  ubuntu-24.04:
    <<: *debian
  ubuntu-26.04:
    <<: *debian
before:
  - mv .packager/Procfile .
  - install -m 0755 .packager/go-pre-compile bin/go-pre-compile
after:
  - mv bin/gogs gogs
after_install: ./.packager/hooks/postinst
buildpack: https://github.com/heroku/heroku-buildpack-go.git#main
