targets:
  debian-9: &debian
    build_dependencies:
      - libpam0g-dev
    dependencies:
      - libpam0g
      - git
  debian-10:
    <<: *debian
  debian-11:
    <<: *debian
  ubuntu-18.04:
    <<: *debian
  ubuntu-20.04:
    <<: *debian
  ubuntu-22.04:
    <<: *debian
  centos-7: &centos
    build_dependencies:
      - pam-devel
      # required for Go buildpack
      - perl-Digest-SHA
    dependencies:
      - pam
      - git
  centos-8:
    <<: *centos
before:
  - mv .packager/Procfile .
after:
  - mv bin/gogs gogs
after_install: ./.packager/hooks/postinst
buildpack: https://github.com/heroku/heroku-buildpack-go.git#main
