version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  frontend:
    container_name: gogs_frontend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8084:3000"
      - "10022:22"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "200k"
    env_file: .env

  postgres:
    container_name: gogs_postgres
    build:
      context: .
      dockerfile: docker/persistence/Dockerfile
#    image: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    ports:
      - "5434:5434"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "200k"
    env_file: .env
    expose:
     - "5434" # Publishes 5434 to other containers but NOT to host machine  
    command: -p 5434
  
  