version: '3'

vars:
  BINARY_EXT:
    sh: echo '{{if eq OS "windows"}}.exe{{end}}'

tasks:
  default:
    deps: [build]
  web:
    desc: Build the binary and start the web server
    deps: [build]
    env:
      GOGS_WORK_DIR: '{{.ROOT_DIR}}'
    cmds:
      - .bin/gogs web

  build:
    desc: Build the binary
    cmds:
      - go build -v
        -ldflags '
          -X "{{.PKG_PATH}}.BuildTime={{.BUILD_TIME}}"
          -X "{{.PKG_PATH}}.BuildCommit={{.BUILD_COMMIT}}"
        '
        -tags '{{.TAGS}}'
        -trimpath -o .bin/gogs{{.BINARY_EXT}} ./cmd/gogs
    vars:
      PKG_PATH: gogs.io/gogs/internal/conf
      BUILD_TIME:
        sh: date -u '+%Y-%m-%d %I:%M:%S %Z'
      BUILD_COMMIT:
        sh: git rev-parse HEAD
    sources:
      - go.mod
      - cmd/gogs/*.go
      - internal/**/*.go
      - conf/**/*
      - public/**/*
      - templates/**/*
      - custom/**/*
    method: timestamp

  generate-schemadoc:
    desc: Generate database schema documentation
    cmds:
      - go generate ./internal/database/schemadoc

  generate:
    desc: Run all go:generate commands
    cmds:
      - go generate ./...

  test:
    desc: Run all tests.
    cmds:
      - go test -cover -race ./...

  clean:
    desc: Cleans up system meta files
    cmds:
      - find . -name "*.DS_Store" -type f -delete

  less:
    desc: Generate CSS from LESS files
    cmds:
      - lessc --clean-css --source-map "public/less/gogs.less" public/css/gogs.min.css

  fixme:
    desc: Show all occurrences of "FIXME"
    cmds:
      - grep -rnw "FIXME" internal

  todo:
    desc: Show all occurrences of "TODO"
    cmds:
      - grep -rnw "TODO" internal

  legacy:
    desc: Identify legacy and deprecated lines
    cmds:
      - grep -rnw "\(LEGACY\|Deprecated\)" internal

  drop-test-db:
    desc: Drop the test database
    cmds:
      - |
        for dbname in $(psql -Xc "copy (select datname from pg_database where datname like 'gogs-%') to stdout"); do
          dropdb "$dbname"
          echo "dropped $dbname"
        done

  lint:
    desc: Run all linters
    cmds:
      - golangci-lint run

  docs:
    desc: Start docs server
    cmds:
      - cd docs && mint dev --port 3333
