#!/bin/sh
#
# $OpenBSD$

daemon="/home/git/gitea/gitea"
daemon_user="git"
daemon_flags="web"

gitea_directory="/home/git/gitea"

rc_bg=YES

. /etc/rc.d/rc.subr

rc_start() {
	${rcexec} "cd ${gitea_directory}; ${daemon} ${daemon_flags} ${_bg}"
}

rc_cmd $1
