name: Bug report
description: File a bug report to help us improve
labels: ["\U0001F48A bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
        - Please use English :)
        - For questions, ask in [Discussions](https://github.com/gogs/gogs/discussions).
        - Before you file an issue read the [Contributing guide](https://github.com/gogs/gogs/blob/main/.github/CONTRIBUTING.md).
        - Check to make sure someone hasn't already opened a similar [issue](https://github.com/gogs/gogs/issues).
  - type: input
    attributes:
      label: Gogs version
      description: |
        Please specify the exact Gogs version you're reporting for, e.g. "0.12.3". You can find the version information in the admin dashboard (`/admin`).
        
        _Note that "gogs/gogs:latest" is not a Gogs version, it does not mean anything._
    validations:
      required: true
  - type: textarea
    attributes:
      label: Git version
      description: |
        Please specify the exact Git version you're using of both server and client. You can find the version information by running `git version`.
      value: |
        - Server: 
        - Client: 
    validations:
      required: true
  - type: input
    attributes:
      label: Operating system
      description: |
        Please specify the exact operating system name and version you're reporting for, e.g. "Windows 10", "CentOS 7", "Ubuntu 20.04".
    validations:
      required: true
  - type: input
    attributes:
      label: Database
      description: |
        Please specify the exact database and version you're reporting for, e.g. "PostgreSQL 9.6", "MySQL 5.7", "SQLite 3".
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To reproduce
      description: The steps to reproduce the problem described above.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Links? References? Suggestions? Anything that will give us more context about the issue you are encountering!
        
        Please include any error logs found in the `log/gogs.log` file. Otherwise, we probably won't be able to help you much.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://go.dev/conduct)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
