#!/bin/sh

# Check if host keys are present, else create them
if ! test -d /data/ssh/ssh_host_key; then
    ssh-keygen -q -f /data/ssh/ssh_host_key -N '' -t rsa1
fi

if ! test -d /data/ssh/ssh_host_rsa_key; then
    ssh-keygen -q -f /data/ssh/ssh_host_rsa_key -N '' -t rsa
fi

if ! test -d /data/ssh/ssh_host_dsa_key; then
    ssh-keygen -q -f /data/ssh/ssh_host_dsa_key -N '' -t dsa
fi

if ! test -d /data/ssh/ssh_host_ecdsa_key; then
    ssh-keygen -q -f /data/ssh/ssh_host_ecdsa_key -N '' -t ecdsa
fi

if ! test -d /data/ssh/ssh_host_ed25519_key; then
    ssh-keygen -q -f /data/ssh/ssh_host_ed25519_key -N '' -t ed25519
fi

# Set correct right to ssh keys
chown -R root:root /data/ssh/*
chmod 600 /data/ssh/*
